# Generated by Django 6.1.1 on 2026-09-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0003_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
